name: Auto Update IP & Cloudflare

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时自动运行
  workflow_dispatch:       # 支持手动触发

jobs:
  run-all:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
      - name: Collect IPs
        run: python collect_ips.py

      - name: Remove invalid and duplicate IPs
        run: python remove_invalid_ips.py

      - name: Update Cloudflare DNS
        run: python bestdomain.py

      - name: Commit changes
        run: |
          git config --global user.email "ohtonarmoht@gmail.com"
          git config --global user.name "ohtonarmoht"
          if [ -n "$(git status --porcelain)" ]; then
            git add ip.txt
            git commit -m "Auto update"
            git push
          else
            echo "No changes to commit."
          fi
