name: Update IP List

on:
  schedule:
    - cron: '0 */4 * * *'  # 每四小时运行一次
  workflow_dispatch:  # 手动触发

jobs:
  update-ip-list:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install beautifulsoup4
        pip install socket
        
    - name: Run script
      run: |
        echo "Running collect_ips.py script..."
        python ${{ github.workspace }}/collect_ips.py
        
    - name: Remove duplicates and unavailable IPs
      run: |
        echo "Removing duplicates and testing IP availability..."
        python -c "import socket; ip_list = open('${{ github.workspace }}/ip.txt').read().splitlines(); ip_list = list(set(ip_list)); valid_ips = []; \
        for ip in ip_list: \
          try: \
            socket.create_connection((ip, 443), timeout=5); \
            valid_ips.append(ip); \
          except Exception as e: \
            print(f'Error for IP {ip}: {e}'); \
        open('${{ github.workspace }}/ip.txt', 'w').writelines('\n'.join(valid_ips))"
        
    - name: Commit and push changes
      run: |
        echo "Committing and pushing changes..."
        git config --global user.email "ohtonarmoht@gmail.com"
        git config --global user.name "ohtonarmoht"
        if [ -n "$(git status --porcelain)" ]; then
          git add ip.txt
          git commit -m "Automatic update"
          git push
        else
          echo "No changes detected, skipping commit."
        fi
