name: Remove Invalid IPs

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时执行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  remove-invalid-ips:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Run remove_invalid_ips.py script
      run: python remove_invalid_ips.py

    - name: Commit and push changes
      run: |
        git config --global user.email "ohtonarmoht@gmail.com"
        git config --global user.name "ohtonarmoht"
        if [ -n "$(git status --porcelain)" ]; then
          git add ip.txt
          git commit -m "Remove invalid IPs"
          git push
        else
          echo "No changes detected, skipping commit."
        fi
